### ISSUE TITLE
フロントエンドインフラ構築

### ISSUE THREAD

**Issue by kota-kamikawa** [kota-kamikawa/rc-sandbox#12]

**Comment by kota-kamikawa** [comment]
@Kyohei-takiyama 

とりあえず、Cloud FrontとS3で構築してみた。ローカルでビルドしたファイルを手動でS3にあげてURLから一応アクセスできるようにはなった。
https://dmuuq596eqcq1.cloudfront.net/

**Comment by Kyohei-takiyama** [comment]
いいね！ないす！

**Comment by Kyohei-takiyama** [comment]
@kota-kamikawa 

このTerraformを参考にGHAから AWSのリソースにOIDCベースでアクセスする用のIAMロールを作って欲しい！そしたら、Push＝＞ビルド＝＞S3に自動デプロイのCIが作れる
https://github.com/Kyohei-takiyama/sample-upload-lambda-deploy-gha/blob/main/terraform/oidc-iam.tf

OIDCの流れは、下記Quitaが参考になる
https://qiita.com/Kyohei-takiyama/items/86e71e1f4f989bbfc665

**Comment by Kyohei-takiyama** [comment]
作成したら、GithubのリポジトリのシークレットファイルにIAMロールのarnの登録よろしく！

**Comment by Kyohei-takiyama** [comment]
あと、tfstateはS3にアップしてほしい！ローカルだと上川さんしか設定値見れんから

**Comment by Kyohei-takiyama** [comment]
諸々Issue作っておいた

**Comment by Kyohei-takiyama** [comment]
CDセットアップ完了
