### ISSUE TITLE
Github <=> AWS にてOIDCで連携するためのIAMロールを作成する

### ISSUE THREAD

**Issue by Kyohei-takiyama** [kota-kamikawa/rc-sandbox#15]
IAMロールの作成後にGIthubシークレットにIAMロールのarnを設定する

**Comment by Kyohei-takiyama** [comment]
https://github.com/kota-kamikawa/rc-sandbox/issues/12#issuecomment-2209142842

**Comment by kota-kamikawa** [comment]
@Kyohei-takiyama 
作成してシークレットに入れといた！多分大丈夫なはず

**Comment by Kyohei-takiyama** [comment]
@kota-kamikawa 
ナイス！
変数名は？？
Settingsが見れないから自分で確認できんのよ

**Comment by kota-kamikawa** [comment]
そうだったね…
`AWS_ROLE_TO_ASSUME`だね

**Comment by Kyohei-takiyama** [comment]
Thank you

**Comment by Kyohei-takiyama** [comment]
CDセットアップ完了！
お疲れした！このIssue閉じて良いと思います
